name: Bug Report
description: Report a bug with the SIR app
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: e.g. Pixel 9, Samsung Galaxy S24
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
      description: e.g. Android 15
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      description: Found in Settings
    validations:
      required: false
